name: voleizinho
description: A new Flutter project.
publish_to: "none"
version: 0.1.2

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  collection: ^1.17.2
  csv: ^5.1.0
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  objectbox: ^2.3.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.1
  share_plus: ^6.3.4
  share_screenshot_widget: ^0.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: poller_one
      fonts:
        - asset: assets/fonts/PollerOne-Regular.ttf
