// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/group.dart';
import 'model/player.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5817927153516367516),
      name: 'Player',
      lastPropertyId: const IdUid(4, 8651932747758421406),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8949873885137698533),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7358579553839099227),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 302019921712395693),
            name: 'dbSkills',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8651932747758421406),
            name: 'groupId',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 3126827991196298943),
      name: 'Group',
      lastPropertyId: const IdUid(4, 6561424085908876837),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2407477485673528843),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3313753390793944440),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 780069684367151973),
            name: 'dbSkillsWeights',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6561424085908876837),
            name: 'usePositionalBalacing',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 3126827991196298943),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Player: EntityDefinition<Player>(
        model: _entities[0],
        toOneRelations: (Player object) => [],
        toManyRelations: (Player object) => {},
        getId: (Player object) => object.id,
        setId: (Player object, int id) {
          object.id = id;
        },
        objectToFB: (Player object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final dbSkillsOffset = object.dbSkills == null
              ? null
              : fbb.writeString(object.dbSkills!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, dbSkillsOffset);
          fbb.addInt64(3, object.groupId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Player()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..dbSkills = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..groupId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);

          return object;
        }),
    Group: EntityDefinition<Group>(
        model: _entities[1],
        toOneRelations: (Group object) => [],
        toManyRelations: (Group object) => {},
        getId: (Group object) => object.id,
        setId: (Group object, int id) {
          object.id = id;
        },
        objectToFB: (Group object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final dbSkillsWeightsOffset = object.dbSkillsWeights == null
              ? null
              : fbb.writeString(object.dbSkillsWeights!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, dbSkillsWeightsOffset);
          fbb.addBool(3, object.usePositionalBalancing);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Group()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..dbSkillsWeights = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..usePositionalBalancing =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Player] entity fields to define ObjectBox queries.
class Player_ {
  /// see [Player.id]
  static final id = QueryIntegerProperty<Player>(_entities[0].properties[0]);

  /// see [Player.name]
  static final name = QueryStringProperty<Player>(_entities[0].properties[1]);

  /// see [Player.dbSkills]
  static final dbSkills =
      QueryStringProperty<Player>(_entities[0].properties[2]);

  /// see [Player.groupId]
  static final groupId =
      QueryIntegerProperty<Player>(_entities[0].properties[3]);
}

/// [Group] entity fields to define ObjectBox queries.
class Group_ {
  /// see [Group.id]
  static final id = QueryIntegerProperty<Group>(_entities[1].properties[0]);

  /// see [Group.name]
  static final name = QueryStringProperty<Group>(_entities[1].properties[1]);

  /// see [Group.dbSkillsWeights]
  static final dbSkillsWeights =
      QueryStringProperty<Group>(_entities[1].properties[2]);

  /// see [Group.usePositionalBalancing]
  static final usePositionalBalacing =
      QueryBooleanProperty<Group>(_entities[1].properties[3]);
}
